# frozen_string_literal: true

# Docs Agent Service
#
# This service generates and maintains project documentation based on
# the project brief, GTM positioning, and product management scope.
#
# Example usage:
#   project_brief = "A collaborative task management tool..."
#   service = DocsAgentService.new(project_brief)
#   result = service.run
#   # => { success: true, files_updated: 3, ... }
#
class DocsAgentService
  attr_reader :project_brief, :gtm_positioning, :work_items

  def initialize(project_brief, gtm_positioning: nil, work_items: nil)
    @project_brief = project_brief
    @gtm_positioning = gtm_positioning || read_gtm_positioning
    @work_items = work_items || WorkItem.tasks
  end

  def run
    Rails.logger.info("Docs Agent: Starting documentation generation")

    # Stub: In production, this would call an LLM API with the prompt to generate docs
    # Generate or update documentation files
    files_updated = []

    # Ensure docs directories exist
    FileUtils.mkdir_p(Rails.root.join("docs"))

    # Update stack.md
    update_stack_doc
    files_updated << "docs/stack.md"

    # Update setup.md
    update_setup_doc
    files_updated << "docs/setup.md"

    # Note: README.md already exists and is comprehensive,
    # so we'll skip updating it unless specifically needed

    Rails.logger.info("Docs Agent: Updated #{files_updated.count} documentation files")

    {
      success: true,
      files_updated: files_updated,
      message: "Successfully updated #{files_updated.count} documentation files"
    }
  rescue StandardError => e
    Rails.logger.error("Docs Agent failed: #{e.message}")
    {
      success: false,
      error: e.message
    }
  end

  private

  # Future: When integrating with LLM, read prompt file here
  # def read_prompt
  #   prompt_path = Rails.root.join("agents", "docs", "prompt.md")
  #   File.read(prompt_path)
  # rescue Errno::ENOENT
  #   Rails.logger.warn("Docs Agent: Prompt file not found at #{prompt_path}")
  #   nil
  # end

  def read_gtm_positioning
    positioning_path = Rails.root.join("docs", "product", "positioning.md")
    File.read(positioning_path)
  rescue Errno::ENOENT
    Rails.logger.warn("Docs Agent: GTM positioning not found")
    nil
  end

  def update_stack_doc
    # Stub implementation - in production, this would use an LLM
    # to generate comprehensive stack documentation
    content = <<~MARKDOWN
      # Technology Stack

      ## Overview

      This project is built with modern, proven technologies optimized for developer productivity and application performance.

      ## Backend

      ### Framework: Ruby on Rails 8.1
      - Latest stable Rails with modern defaults
      - Hotwire for reactive UIs without complex JavaScript
      - Solid Queue for background job processing

      ### Database: PostgreSQL
      - Primary data store
      - Full-text search capabilities
      - JSONB for flexible data structures

      ### Background Jobs: Solid Queue
      - Database-backed job queue
      - No Redis dependency
      - Built-in Rails 8

      ## Frontend

      ### CSS: Tailwind CSS
      - Utility-first CSS framework
      - Responsive design built-in
      - Minimal custom CSS required

      ### JavaScript: Hotwire (Turbo + Stimulus)
      - Turbo for page updates without full reloads
      - Stimulus for progressive enhancement
      - Minimal JavaScript footprint

      ### Build: esbuild
      - Fast JavaScript bundling
      - TypeScript support
      - Minimal configuration

      ## Development Tools

      ### Testing: RSpec
      - Unit tests for models and services
      - Request specs for API endpoints
      - System specs for end-to-end flows

      ### Linting: RuboCop (GitHub preset)
      - Consistent Ruby code style
      - Automatic formatting
      - Pre-commit hooks

      ### Security
      - Brakeman for static analysis
      - bundler-audit for dependency scanning
      - Regular dependency updates

      ## Patterns and Conventions

      ### Service Objects
      - Complex business logic lives in service classes
      - Services are in `app/services/`
      - One public method: `#run` or `#call`

      ### Background Jobs
      - All async work uses Solid Queue
      - Jobs are in `app/jobs/`
      - Jobs are idempotent when possible

      ### Frontend
      - Turbo Frames for partial page updates
      - Stimulus controllers for interactions
      - Tailwind utilities, minimal custom CSS

      ## Dependencies

      See `Gemfile` for Ruby dependencies and `package.json` for JavaScript dependencies.

      ---

      *Generated by Docs Agent on #{Time.current.to_s(:long)}*
    MARKDOWN

    File.write(Rails.root.join("docs", "stack.md"), content)
  end

  def update_setup_doc
    # Stub implementation - in production, this would use an LLM
    content = <<~MARKDOWN
      # Development Setup

      ## Prerequisites

      Ensure you have the following installed:

      - **Ruby 3.2+**: Check with `ruby --version`
      - **PostgreSQL 14+**: Check with `psql --version`
      - **Node.js 20+**: Check with `node --version`
      - **Git**: Check with `git --version`

      ## Installation

      ### 1. Clone the Repository

      ```bash
      git clone https://github.com/mitchellfyi/synorg.git
      cd synorg
      ```

      ### 2. Run Setup Script

      ```bash
      bin/setup
      ```

      This idempotent script will:
      - Install Ruby dependencies (bundler)
      - Install JavaScript dependencies (npm)
      - Create and migrate databases
      - Install Git hooks (Lefthook)

      ### 3. Start the Development Server

      ```bash
      bin/dev
      ```

      This starts:
      - Rails server on port 3000
      - Solid Queue worker for background jobs
      - JavaScript build watcher (esbuild)
      - CSS build watcher (Tailwind)

      Visit http://localhost:3000

      ## Common Tasks

      ### Running Tests

      ```bash
      # All tests
      bin/test

      # Specific test file
      bin/test spec/models/work_item_spec.rb
      ```

      ### Linting and Formatting

      ```bash
      # Check everything
      bin/lint

      # Auto-fix issues
      bin/format
      ```

      ### Database

      ```bash
      # Create database
      bin/rails db:create

      # Run migrations
      bin/rails db:migrate

      # Reset database
      bin/rails db:reset
      ```

      ## Troubleshooting

      ### PostgreSQL Not Running

      ```bash
      # macOS
      brew services start postgresql

      # Linux
      sudo service postgresql start
      ```

      ### Dependencies Out of Date

      ```bash
      bundle install
      npm install
      ```

      ---

      *Generated by Docs Agent on #{Time.current.to_s(:long)}*
    MARKDOWN

    File.write(Rails.root.join("docs", "setup.md"), content)
  end
end
