# RuboCop configuration with GitHub preset
inherit_gem:
  rubocop-github:
    - config/default.yml

plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/queue_schema.rb'
    - 'db/cache_schema.rb'
    - 'db/cable_schema.rb'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'

# Disable I18n locale texts cop - not using i18n yet
Rails/I18nLocaleTexts:
  Enabled: false

# Allow multiple expectations in request specs (they test full workflows)
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/integration/**/*'

# Allow longer examples in request/integration specs
RSpec/ExampleLength:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/integration/**/*'

# Allow multiple memoized helpers in specs
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/**/*'

# Allow create_list with more than 10 items in tests
FactoryBot/ExcessiveCreateList:
  Enabled: false
# Overrides can go here if needed

